all: learning doublet

learning: learning/learning.cpp
	g++ -g -Wall -std=c++11 learning/learning.cpp -o learning/learning

doublet: heap/doublet.cpp
	g++ -g -Wall -std=c++11 heap/doublet.cpp -o heap/doublet