all: learning heap doublet

learning: learning/learning.cpp
	g++ -g -Wall -std=c++11 learning/learning.cpp -o learning/learning

heap: heap/heap.h heap/heap.cpp
	g++ -g -Wall -std=c++11 heap/heap.cpp -o heap/heap

doublet: heap/doublet.cpp
	g++ -g -Wall -std=c++11 heap/doublet.cpp -o heap/doublet